### PR TITLE
fix: log redis errors and return generic error msg

### LINKED ISSUE #22: Redis bloom filter error handling improvement
# Problem

I tried swapping the suggested redis-stack-server out for [valkey-bundle](https://hub.docker.com/r/valkey/valkey-bundle) ([docs](https://valkey.io/topics/valkey-bundle/)), as at a glance it appeared to be a suitable replacement. After some errors and investigating further it seems like that would require switching redis libraries, which is out of scope for this issue.

I think the error handling of this situation could've been improved though. initially the logs looked fine at startup, and nothing more was logged while submitting requests:

```
2025/11/07 00:51:50 DIFFICULTY not set or invalid (''), using default: 4
2025/11/07 00:51:50 ALLOWED_ORIGINS not set, using default: [*]
2025/11/07 00:51:50 Loaded Ed25519 private key from /data/wicketkeeper.key
2025/11/07 00:51:50 REDIS_DB not set or invalid (''), using default: 0
2025/11/07 00:51:50 Successfully connected to Redis at redis:6379 DB 0.
2025/11/07 00:51:50 Captcha Service Public Key (hex): 86a97acbf73ddce4e624103c02a5de13ee0307c0075f67128e12e450edd4c472
2025/11/07 00:51:50 Wicketkeeper service listening on :8080 …
2025/11/07 00:51:50 Global Difficulty: 4
2025/11/07 00:51:50 Allowed Origins: [*]
```

But API requests to `siteverify` were returning 500 errors, with this content: 

`bloom filter initialization error: redis BF.RESERVE captcha:spent:20251107T0033 failed: ERROR`

# Suggested Changes

- log this error to stdout in addition to issuing a 500 error [here](https://github.com/a-ve/wicketkeeper/blob/bc319a0c97db91a2ad014aeb737fef9f34161e64/server/handlers.go#L40)
- I don't think this verbose of information should be returned to the client in the HTTP response, and something generic should be returned instead
- This also suggests that the [bloomfilter test at startup ](https://github.com/a-ve/wicketkeeper/blob/bc319a0c97db91a2ad014aeb737fef9f34161e64/server/server.go#L47) may not be representative enough of later usage

If these changes are acceptable, I'd be happy to open a PR!

### PR DESCRIPTION
**Pull request by holysoles**
This PR returns less information to the client about specific redis errors, but still logs the existing verbose information to stdout.

Closes #22

### CODE REVIEW

**Review by maxlerebourg — APPROVED** [review]

File: server/handlers.go [hunk 1]
```diff
@@ -189,7 +189,8 @@ func (s *Server) VerifyChallenge(w http.ResponseWriter, r *http.Request) {
 	sliceKey := bloomKey(iatTime)
 
 	if err := s.ensureBloom(ctx, sliceKey); err != nil {
-		http.Error(w, "bloom filter initialization error: "+err.Error(), http.StatusInternalServerError)
+		log.Printf("bloom filter initialization error: " + err.Error())
```
Comment (maxlerebourg) [inline server/handlers.go]: use `log.Printf("bloom filter initialization error: %v", err)` like on the untouched line 201
